[workspace]
members = ["quinn", "quinn-proto", "quinn-test", "quinn-udp", "quinn-visibility", "bench", "perf", "fuzz"]
default-members = ["quinn", "quinn-proto", "quinn-test", "quinn-udp", "quinn-visibility", "bench", "perf"]

[profile.bench]
debug = true

[profile.release]
debug = true
